name: Test cli.sh

on:
  push:
  workflow_dispatch:

jobs:
  local_install_script:
    name: local install script - ${{matrix.os}} - ${{matrix.shell}} - ${{matrix.ruby-version}}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby-version: [2.6.10,3.0.4,3.1.2,3.2.2,3.3.0-preview1]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: remove system installed ruby
        run : |
          ruby --version
          sudo rm -rf /usr/bin/ruby
          sudo apt-get --purge remove ruby-full
        if: env.ACT != 'true'
      - name: remove system installed linuxbrew
        run : |
          /home/linuxbrew/.linuxbrew/bin/brew --version
          sudo rm -rf /home/linuxbrew
        if: env.ACT != 'true'
      - run: |
          /bin/sh -c 'curl -fsSL https://gist.githubusercontent.com/YOU54F/2e47eb0b653b6810dd6a0be9fc6820ea/raw/install.sh' | sh -s -- --ci -v ${{ matrix.ruby-version }}
        name: install traveling-ruby ${{ matrix.ruby-version }} via ${{ matrix.shell }}
      - run: ruby --version
        name: ruby --version via ${{ matrix.shell }}
      - name: install homebrew
        run: |
          export PATH=${PATH}:/home/linuxbrew/.linuxbrew/bin
          echo "PATH=/root/.travelling-ruby/bin:${PATH}" >>$GITHUB_ENV
          echo $PATH
          NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/you54f/install/HEAD/install.sh)" || true
          echo "Homebrew installed"
          brew --version