name: Test cli.sh

on:
  push:
  workflow_dispatch:

jobs:
  local_install_script:
    name: local install script - ${{matrix.os}} - ${{matrix.shell}} - ${{matrix.ruby-version}}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby-version: [2.6.10]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - run : |
          which ruby
          ruby --version
          # rm -rf $HOME/linuxbrew
          sudo apt-get --purge remove ruby-full
        if: runner.os == 'Linux'
      - run: |
          /bin/sh -c 'curl -fsSL https://gist.githubusercontent.com/YOU54F/2e47eb0b653b6810dd6a0be9fc6820ea/raw/install.sh' | sh -s -- --ci -v ${{ matrix.ruby-version }}
        name: install traveling-ruby ${{ matrix.ruby-version }} via ${{ matrix.shell }}
      - run: ruby --version
        name: ruby --version via ${{ matrix.shell }}
      - name: install homebrew
        run: |
          export PATH=/home/linuxbrew/.linuxbrew/bin:${PATH}
          echo "PATH=${PATH}" >>$GITHUB_ENV
          NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/you54f/install/HEAD/install.sh)" || true
          echo "Homebrew installed"
          brew --version